version: 2.1
tagged_build_filters: &tagged_build_filters
  branches:
    ignore: /.*/
  tags:
    only: /v[0-9]+\.[0-9]+\.[0-9]+/
test_build_filters: &test_build_filters
  branches:
    only: /.*/
  tags:
    ignore: /v[0-9]+\.[0-9]+\.[0-9]+/
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - run: bundle install
      - run: rubocop -c .rubocop.yml -a
  build:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            PKG_VERSION=$(grep VERSION lib/version.rb | cut -d'"' -f2)
            if [[ "${CIRCLE_TAG}" != "v${PKG_VERSION}" ]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${CIRCLE_TAG}"
              echo "  PKG_VERSION: v${PKG_VERSION}"
              exit 1
            fi
      - run: gem build logdna-rails.gemspec
      - persist_to_workspace:
          root: .
          paths:
            - ./logdna-rails-*.gem
  app2pub:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - persist_to_workspace:
          root: .
          paths:
            - ./logdna-rails-*.gem
  publish:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: .
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: Create a Release
          command: |
            ghr \
              -n "LogDNA Rails Logger ${CIRCLE_TAG}" \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -draft ${CIRCLE_TAG} ${CIRCLE_WORKING_DIRECTORY}
      - persist_to_workspace:
          root: .
          paths:
            - ./logdna-rails-*.gem
  app2rel:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - persist_to_workspace:
          root: .
          paths:
            - ./logdna-rails-*.gem
  release:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - attach_workspace:
          at: .
      - run: gem push logdna-rails-*.gem -k ${RUBYGEMS_API_KEY}
workflows:
  update:
    jobs:
      - test:
          filters: *tagged_build_filters
      - build:
          requires:
            - test
          filters: *tagged_build_filters
      - app2pub:
          type: approval
          requires:
            - build
          filters: *tagged_build_filters
      - publish:
          requires:
            - app2pub
          filters: *tagged_build_filters
      - app2rel:
          type: approval
          requires:
            - publish
          filters: *tagged_build_filters
      - publish:
          requires:
            - app2rel
          filters: *tagged_build_filters
  test:
    jobs:
      - test:
          filters: *test_build_filters
